version: "3.9"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blackjack
    ports:
      - "3307:3306"   # MySQL expuesto en el host en el puerto 3307
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

  blackjack-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blackjack-app
    restart: always
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      # Sobreescribe el application.yml dentro del contenedor
      R2DBC_URL: r2dbc:mysql://mysql-db:3306/blackjack
      R2DBC_USER: root
      R2DBC_PASS: root
      MONGODB_URI: mongodb://host.docker.internal:27017/blackjack
      SERVER_PORT: 8080

volumes:
  mysql_data:
